### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by practicalswift**
Fix typos.

Sorry for this boring first-time contribution. I hope to be able to make more interesting contributions in the future.

### CODE REVIEW

**Comment by EBGToo** [comment]
> Fix typos.
> 
> Sorry for this boring first-time contribution. I hope to be able to make more interesting contributions in the future.

If possible can you fix typos on the 'crypto' branch instead?

**Comment by practicalswift** [comment]
@EBGToo Sure! Are the meaning of the different branches documented somewhere? Is `crypto` the development branch and `master` the stable branch?

**Comment by EBGToo** [comment]
Not documented but effectively, as you surmised, `crypto` is the development branch.

**Comment by EBGToo** [comment]
Master will be updated soon; a spell check then would be great.

**Pull request closed without merging**
