### PR TITLE
Add Litecoin chainparams

### PR DESCRIPTION
**Pull request by losh11**
Adds basic litecoin mainnet/testnet support.

### CODE REVIEW

**Comment by samuraisam** [comment]
Hi there, thank you for submitting this. Sorry I did not see this earlier. Do you have a working example of this? Does it "just work"?

**Comment by kinosang** [comment]
@samuraisam is there any ETA?

**Comment by kinosang** [comment]
almost four years passed, any update?

**Comment by EBGToo** [comment]
@losh11 Your commit for 'chainparams' has been integrated into the active repository at https://github.com/blockset-corp/walletkit on branch `feature/CORE-1179`.  Thanks.  Cheers.

**Comment by losh11** [comment]
Thanks Ed!

**Pull request closed without merging**
