### PR TITLE
CORE-506: Add System.updateNetworkFees

### PR DESCRIPTION
**Pull request by michael-brd**
@EBGToo, I noticed the Swift sets the networks fees at the Swift level only (I implemented the Java in the same way). Did we want to set those values at the C level?

### CODE REVIEW

**Comment by EBGToo** [comment]
So this is the issue that the Network CTOR does:
```
       fees.forEach { cryptoNetworkAddNetworkFee (core, $0.core) }
```
thereby keeping `Network.fees` consistent with `BRCryptoNetwork`?  And the on update we get out-of-sync?

Instead `Network.fees` should be a 'computed property', mapping over (`get`) or installing (`set`) the Crypto C values?

**Comment by michael-brd** [comment]
> So this is the issue that the Network CTOR does:
> 
> ```
>        fees.forEach { cryptoNetworkAddNetworkFee (core, $0.core) }
> ```
> 
> thereby keeping `Network.fees` consistent with `BRCryptoNetwork`? And the on update we get out-of-sync?
> 
> Instead `Network.fees` should be a 'computed property', mapping over (`get`) or installing (`set`) the Crypto C values?

Correct; C is out of sync with Java/Swift after an update.

**Comment by EBGToo** [comment]
They should be in sync.

**Comment by michael-brd** [comment]
> They should be in sync.

Agreed. Separate issue to add C functionality and update Swift/Java?

**Pull request merged**
