### PR TITLE
CORE-633: Fix fileServiceTypeBlockV1Reader to pass the block buffer l…

### PR DESCRIPTION
**Pull request by michael-brd**
…ength

### CODE REVIEW

**Comment by michael-brd** [comment]
> Given that BRWalletManger.c contains:
> 
> ```
> static BRFileServiceTypeSpecification fileServiceSpecifications[]
> ```
> 
> as a `static` there isn't a way to add a test case to confirm the parsing? `#if defined (DEBUG) extern #else static #endif`?

That would would work. Since you authored the `fileService` "class", are you able to write the tests for the various operations?

**Comment by EBGToo** [comment]
Let me give it a quick try; it would be in testBWM.c.  If it takes more than 1 hour, we'll add another JIRA for later.

**Comment by EBGToo** [comment]
@michael-brd Added a test case covering blocks, transactions, peers.  Modified the writer/reader for BRPeer to ensure endian agnostic saving.

**Comment by michael-brd** [comment]
> @michael-brd Added a test case covering blocks, transactions, peers. Modified the writer/reader for BRPeer to ensure endian agnostic saving.

Great! I'll merge on approval.

**Pull request merged**
